options:
  check_parameters:
    type: string
    default: ""
    description: |
      The parameters for the check_lsi_raid check.
      See 'check_lsi_raid --help' for more information.
  check_repo:
    type: string
    default: "https://github.com/thomas-krenn/check_lsi_raid.git"
    description: |
      The repository to clone the check_lsi_raid plugin from.
  check_version:
    type: string
    default: "2f28ea4969c0c4c9d6928a323a6130e26261062e"
    description: |
      The versions of the check_lsi_raid repository to check out.
      This can be a branch, tag or hash.
      See 'version' parameter in https://docs.ansible.com/ansible/latest/modules/git_module.html for more information.
  storcli_path:
    type: string
    default: "/opt/MegaRAID/storcli/storcli64"
    description: |
      The path to the StorCLI executable.
      The default path is from the upstream StorCLI package.
  storcli_url:
    type: string
    default: "https://docs.broadcom.com/docs-and-downloads/raid-controllers/raid-controllers-common-files/MR_SAS_Unified_StorCLI_007.1108.0000.0000.zip"
    description: |
      The URL to an archived StorCLI package.
      Default is the upstream Broadcom download page.
      See https://www.broadcom.com/support/download-search for other versions.
